# For ec2 instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: springboot
        image: vignan91/java_spring:8081
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30036  # Optional, specify a port in the 30000-32767 range


# for Wsl
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: springboot-deployment
#   labels:
#     app: spring
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: spring
#   template:
#     metadata:
#       labels:
#         app: spring
#     spec:
#       containers:
#       - name: springboot
#         image: springboot:latest
#         ports:
#         - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-service
#   labels:
#     app: spring
# spec:
#   type: NodePort
#   selector:
#     app: spring
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
